-- Database schema for CBBC FTP Worker
-- Run this against your PostgreSQL database

-- Staging tables for raw data
CREATE TABLE IF NOT EXISTS products_staging (
    product_code TEXT PRIMARY KEY,
    categories TEXT,
    family TEXT,
    parent TEXT,
    one_variant BOOLEAN,
    customs_pos TEXT,
    product_model_name_en TEXT,
    product_model_name_fi TEXT,
    product_model_name_sv TEXT,
    vendor_name TEXT,
    country_origin TEXT,
    vak_code TEXT,
    yk_no TEXT,
    supplier_product_code TEXT,
    catalog_restriction TEXT,
    material TEXT,
    make_model TEXT,
    brand TEXT,
    short_description_en TEXT,
    short_description_fi TEXT,
    short_description_sv TEXT,
    long_description_en TEXT,
    long_description_fi TEXT,
    long_description_sv TEXT,
    product_name_en TEXT,
    product_name_fi TEXT,
    product_name_sv TEXT,
    barcode TEXT,
    compound TEXT,
    lug_height NUMERIC,
    lug_height_unit TEXT,
    oem_number TEXT,
    tyre_studs TEXT,
    tyre_ply_rating TEXT,
    waterproof TEXT,
    foldable TEXT,
    bolt_pattern TEXT,
    top_hole_diameter NUMERIC,
    top_hole_diameter_unit TEXT,
    top_eyelet_width NUMERIC,
    top_eyelet_width_unit TEXT,
    bottom_hole_diameter NUMERIC,
    bottom_hole_diameter_unit TEXT,
    bottom_eyelet_width NUMERIC,
    bottom_eyelet_width_unit TEXT,
    construction TEXT,
    intercom_range TEXT,
    bulb_base TEXT,
    resistor TEXT,
    handlebar_clamp_diameter NUMERIC,
    handlebar_clamp_diameter_unit TEXT,
    front_rear_tyre TEXT,
    mounting_kit_included TEXT,
    winch_max_capacity NUMERIC,
    winch_max_capacity_unit TEXT,
    tyre_weight_index TEXT,
    tyre_speed_rating TEXT,
    power_light TEXT,
    power_light_unit TEXT,
    helmet_safety_system TEXT,
    studs_count INTEGER,
    valve_type TEXT,
    valve_length NUMERIC,
    valve_length_unit TEXT,
    bicycle_brake_type TEXT,
    handlebar_rise NUMERIC,
    handlebar_rise_unit TEXT,
    buoyancy NUMERIC,
    buoyancy_unit TEXT,
    bicycle_brake_model TEXT,
    bicycle_wheel_hub TEXT,
    clothing_size TEXT,
    gender TEXT,
    has_membrane TEXT,
    package_weight NUMERIC,
    package_weight_unit TEXT,
    package_height NUMERIC,
    package_height_unit TEXT,
    package_width NUMERIC,
    package_width_unit TEXT,
    package_length NUMERIC,
    package_length_unit TEXT,
    packing_size TEXT,
    certifications TEXT,
    size TEXT,
    tyre_rim_size NUMERIC,
    tyre_rim_size_unit TEXT,
    tyre_height NUMERIC,
    tyre_height_unit TEXT,
    tyre_width NUMERIC,
    tyre_width_unit TEXT,
    max_load NUMERIC,
    max_load_unit TEXT,
    etrto_size TEXT,
    track_length NUMERIC,
    track_length_unit TEXT,
    track_width NUMERIC,
    track_width_unit TEXT,
    track_pitch NUMERIC,
    track_pitch_unit TEXT,
    rim_width NUMERIC,
    rim_width_unit TEXT,
    cc_max NUMERIC,
    cc_max_unit TEXT,
    cc_min NUMERIC,
    cc_min_unit TEXT,
    spokes_length NUMERIC,
    spokes_length_unit TEXT,
    product_weight NUMERIC,
    product_weight_unit TEXT,
    product_height NUMERIC,
    product_height_unit TEXT,
    product_width NUMERIC,
    product_width_unit TEXT,
    product_length NUMERIC,
    product_length_unit TEXT,
    sparkplug_thread_length NUMERIC,
    thickness NUMERIC,
    thickness_unit TEXT,
    diameter NUMERIC,
    diameter_unit TEXT,
    inner_diameter NUMERIC,
    inner_diameter_unit TEXT,
    outer_diameter NUMERIC,
    outer_diameter_unit TEXT,
    riser_height NUMERIC,
    riser_height_unit TEXT,
    oil_type TEXT,
    oil_viscosity TEXT,
    oil_volume NUMERIC,
    oil_volume_unit TEXT,
    oil_stroke TEXT,
    sprocket_front TEXT,
    sprocket_rear TEXT,
    drive_chain_pitch TEXT,
    chain_links TEXT,
    sprocket_internal_splines TEXT,
    chain_guard TEXT,
    drive_chain_lock_type TEXT,
    drive_chain_seal_type TEXT,
    drive_pitch TEXT,
    lens_colour TEXT,
    touch_screen_compatible TEXT,
    sparkplug_seat_configuration TEXT,
    silencer_fitment TEXT,
    teeth_count INTEGER,
    pre_drilled TEXT,
    clamp_on TEXT,
    sunvisor TEXT,
    sparkplug_heat_rating TEXT,
    volume NUMERIC,
    volume_unit TEXT,
    colour_en TEXT,
    colour_fi TEXT,
    colour_sv TEXT,
    colour_property_en TEXT,
    colour_property_fi TEXT,
    colour_property_sv TEXT,
    derailleur_gears_speed TEXT,
    bag_type TEXT,
    lens_type TEXT,
    battery_type TEXT,
    filter_type TEXT,
    track_type TEXT,
    bulb_type TEXT,
    transmission_type TEXT,
    jet_type TEXT,
    suspension TEXT,
    riding_style TEXT,
    adjustability_type TEXT,
    helmet_type TEXT,
    lever_type TEXT,
    light_part_type TEXT,
    silencer_type TEXT,
    cable_type TEXT,
    bearing_kit_type TEXT,
    lifejacket_type TEXT,
    battery_cca NUMERIC,
    battery_cca_unit TEXT,
    battery_capacity NUMERIC,
    "battery_capacity-unit" TEXT, -- Changed from battery_capacity_unit to match error message
    category_codes TEXT[], -- Added category_codes directly
    created TIMESTAMPTZ,
    updated TIMESTAMPTZ,
    raw_hash TEXT,
    imported_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prices_staging (
    product_code TEXT PRIMARY KEY,
    eur_excl_vat NUMERIC,
    eur_incl_vat NUMERIC,
    eur_excl_vat_eu NUMERIC,
    eur_incl_vat_eu NUMERIC,
    sek_excl_vat NUMERIC,
    sek_incl_vat NUMERIC,
    nok_excl_vat NUMERIC,
    nok_incl_vat NUMERIC,
    gbp_excl_vat NUMERIC,
    dkk_excl_vat NUMERIC,
    dkk_incl_vat NUMERIC,
    imported_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_staging (
    product_code TEXT,
    ean TEXT,
    vaasa INTEGER,
    sweden INTEGER,
    total INTEGER,
    source TEXT, -- 'product_code' or 'ean'
    imported_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (product_code, source)
);

CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    code TEXT,
    description TEXT,
    language_number INTEGER
);

CREATE TABLE IF NOT EXISTS category_hierarchy (
    id TEXT PRIMARY KEY,
    prev_category TEXT,
    category_level INTEGER
);

CREATE TABLE IF NOT EXISTS images_staging (
    product_code TEXT,
    image_url TEXT,
    image_name TEXT,
    imported_at TIMESTAMPTZ DEFAULT NOW()
);

-- Production tables
CREATE TABLE IF NOT EXISTS products (
    product_code TEXT PRIMARY KEY,
    name_en TEXT,
    name_fi TEXT,
    name_sv TEXT,
    brand TEXT,
    category_codes TEXT[],
    price_eur_excl_vat NUMERIC,
    price_eur_incl_vat NUMERIC,
    stock_total INTEGER,
    stock_vaasa INTEGER,
    stock_sweden INTEGER,
    barcode TEXT,
    vendor_name TEXT,
    catalog_restriction TEXT,
    image_url TEXT,
    imported_at TIMESTAMPTZ,
    last_synced_at TIMESTAMPTZ,
    status TEXT -- 'valid', 'missing_price', 'missing_stock', 'invalid'
);

CREATE TABLE IF NOT EXISTS ecwid_sync_logs (
    product_code TEXT,
    ecwid_item_id TEXT,
    synced_at TIMESTAMPTZ,
    status TEXT, -- 'success', 'failed'
    message TEXT,
    PRIMARY KEY (product_code, synced_at)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_products_staging_imported_at ON products_staging (imported_at);
CREATE INDEX IF NOT EXISTS idx_prices_staging_imported_at ON prices_staging (imported_at);
CREATE INDEX IF NOT EXISTS idx_stock_staging_imported_at ON stock_staging (imported_at);
CREATE INDEX IF NOT EXISTS idx_images_staging_imported_at ON images_staging (imported_at);
CREATE INDEX IF NOT EXISTS idx_products_status ON products (status);
CREATE INDEX IF NOT EXISTS idx_products_imported_at ON products (imported_at);
CREATE INDEX IF NOT EXISTS idx_ecwid_sync_logs_synced_at ON ecwid_sync_logs (synced_at);
